# Generated by Django 6.0.1 on 2026-01-07 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('radius_meters', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'office_locations',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('department', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Surveyors', 'Surveyors'), ('Accounts', 'Accounts'), ('Growth', 'Growth'), ('Others', 'Others')], max_length=20)),
                ('primary_office', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('admin', 'Admin')], default='employee', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employees',
                'indexes': [models.Index(fields=['username'], name='employees_usernam_b4c359_idx'), models.Index(fields=['email'], name='employees_email_f66e96_idx'), models.Index(fields=['department'], name='employees_departm_ef7a1f_idx'), models.Index(fields=['is_active'], name='employees_is_acti_e91717_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('alternate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('certificates_summary', models.TextField(blank=True, null=True)),
                ('home_address', models.TextField(blank=True, null=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('skill_set', models.TextField(blank=True, null=True)),
                ('reporting_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('planned_leaves', models.IntegerField(default=0)),
                ('unplanned_leaves', models.IntegerField(default=0)),
                ('professional_training', models.TextField(blank=True, null=True)),
                ('family_details', models.TextField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('other', 'Other')], max_length=20, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('documents_pdf_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='attendance.employee')),
            ],
            options={
                'db_table': 'employee_profiles',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('photo', 'Photo'), ('signature', 'Signature'), ('aadhar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('other_id', 'Other ID'), ('highest_qualification', 'Highest Qualification'), ('professional_certificate', 'Professional Certificate'), ('other_qualification', 'Other Qualification')], max_length=50)),
                ('doc_name', models.CharField(max_length=100)),
                ('doc_number', models.CharField(blank=True, max_length=100, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='attendance.employee')),
            ],
            options={
                'db_table': 'employee_documents',
                'indexes': [models.Index(fields=['employee', 'doc_type'], name='employee_do_employe_384c00_idx')],
            },
        ),
        migrations.CreateModel(
            name='DepartmentOfficeAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Surveyors', 'Surveyors'), ('Accounts', 'Accounts'), ('Growth', 'Growth'), ('Others', 'Others')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_access', to='attendance.officelocation')),
            ],
            options={
                'db_table': 'department_office_access',
                'unique_together': {('department', 'office')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('office', 'Office'), ('wfh', 'Work From Home'), ('client', 'Client')], max_length=20)),
                ('status', models.CharField(choices=[('present', 'Present'), ('half_day', 'Half Day'), ('wfh', 'Work From Home'), ('client', 'Client'), ('absent', 'Absent')], max_length=20)),
                ('check_in_location', models.JSONField(blank=True, null=True)),
                ('check_out_location', models.JSONField(blank=True, null=True)),
                ('check_in_photo', models.TextField(blank=True, null=True)),
                ('check_out_photo', models.TextField(blank=True, null=True)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('is_half_day', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.employee')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='attendance.officelocation')),
            ],
            options={
                'db_table': 'attendance_records',
                'indexes': [models.Index(fields=['employee', 'date'], name='attendance__employe_6b3da7_idx'), models.Index(fields=['date'], name='attendance__date_19baa0_idx'), models.Index(fields=['type'], name='attendance__type_f86ff2_idx'), models.Index(fields=['status'], name='attendance__status_5b1243_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WFHRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wfh_requests', to='attendance.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_wfh_requests', to='attendance.employee')),
            ],
            options={
                'db_table': 'wfh_requests',
                'indexes': [models.Index(fields=['employee'], name='wfh_request_employe_e709ae_idx'), models.Index(fields=['status'], name='wfh_request_status_18e960_idx'), models.Index(fields=['requested_date'], name='wfh_request_request_c75f33_idx')],
                'unique_together': {('employee', 'requested_date')},
            },
        ),
    ]
