# Generated by Django 6.0.1 on 2026-01-21 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_leaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('wfh', 'Work From Home'), ('full_day_leave', 'Full Day Leave'), ('half_day_leave', 'Half Day Leave')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee_requests',
            },
        ),
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='leave_reque_employe_b797ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='leave_reque_status_401183_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='leave_reque_start_d_e77766_idx',
        ),
        migrations.AlterUniqueTogether(
            name='wfhrequest',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='wfhrequest',
            name='wfh_request_employe_e709ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='wfhrequest',
            name='wfh_request_status_18e960_idx',
        ),
        migrations.RemoveIndex(
            model_name='wfhrequest',
            name='wfh_request_request_c75f33_idx',
        ),
        migrations.AddField(
            model_name='employeerequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='attendance.employee'),
        ),
        migrations.AddField(
            model_name='employeerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to='attendance.employee'),
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='wfhrequest',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='wfhrequest',
            name='reviewed_by',
        ),
        migrations.AddIndex(
            model_name='employeerequest',
            index=models.Index(fields=['employee'], name='employee_re_employe_6ccd85_idx'),
        ),
        migrations.AddIndex(
            model_name='employeerequest',
            index=models.Index(fields=['status'], name='employee_re_status_4ff3e7_idx'),
        ),
        migrations.AddIndex(
            model_name='employeerequest',
            index=models.Index(fields=['start_date'], name='employee_re_start_d_469845_idx'),
        ),
        migrations.AddIndex(
            model_name='employeerequest',
            index=models.Index(fields=['request_type'], name='employee_re_request_8fa918_idx'),
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
        migrations.DeleteModel(
            name='WFHRequest',
        ),
    ]
