# Generated by Django 6.0.1 on 2026-01-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_employeerequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequest',
            name='request_type',
            field=models.CharField(choices=[('wfh', 'Work From Home'), ('full_day', 'Full Day Leave'), ('half_day', 'Half Day Leave')], max_length=20),
        ),
    ]
