# Generated by Django 6.0.1 on 2026-01-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_employeerequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerequest',
            name='half_day_period',
            field=models.CharField(blank=True, choices=[('first_half', 'First Half'), ('second_half', 'Second Half')], max_length=20, null=True),
        ),
    ]
