# Generated by Django 6.0.1 on 2026-01-27 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_employeerequest_half_day_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_wishes', to='attendance.employee')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_wishes', to='attendance.employee')),
            ],
            options={
                'db_table': 'birthday_wishes',
                'indexes': [models.Index(fields=['receiver'], name='birthday_wi_receive_13298e_idx'), models.Index(fields=['is_read'], name='birthday_wi_is_read_37001b_idx'), models.Index(fields=['created_at'], name='birthday_wi_created_32f2ce_idx')],
            },
        ),
    ]
