# Generated by Django 6.0.1 on 2026-01-28 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_employee_manager_alter_employee_role_taskcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_tasks', to='attendance.employee'),
        ),
    ]
